name: storify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3
  pie_chart: ^5.4.0
  fl_chart: ^0.70.2
  http: ^1.3.0
  syncfusion_flutter_xlsio: ^29.1.35
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.12
  geolocator: ^14.0.0
  cached_network_image: ^3.4.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/google.svg
    - assets/images/apple.svg
    - assets/images/changePass.svg 
    - assets/images/emailcheck.svg  
    - assets/images/emailSnack.svg    
    - assets/images/changePassword.svg
    - assets/images/passChanged.svg
    - assets/images/home.svg
    - assets/images/products.svg
    - assets/images/orders.svg
    - assets/images/stores.svg
    - assets/images/search.svg
    - assets/images/noti.svg
    - assets/images/me.png
    - assets/images/filter.svg
    - assets/images/totalProducts.svg
    - assets/images/arrow_up.svg
    - assets/images/totalPaidOrders.svg
    - assets/images/totalUsers.svg
    - assets/images/totalStores.svg
    - assets/images/settings.svg
    - assets/images/settings2.svg
    - assets/images/logout.svg
    - assets/images/image3.png
    - assets/images/back.svg
    - assets/images/category.svg
    - assets/images/map.svg
    - assets/images/addCat.svg
    - assets/images/gallery.svg
    - assets/images/Managment.svg
    - assets/images/totalorders.svg
    - assets/images/Activeorders.svg
    - assets/images/completedOrders.svg
    - assets/images/cancorders.svg
    - assets/images/truck.svg
    - assets/images/history.svg

